import '../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './Providers';
import Layout from '@/components/Layout';

export const metadata = {
  title: 'My RainbowKit App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
